# Generated by Django 5.1.1 on 2024-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField(db_index=True, max_length=50)),
                ('memo', models.TextField(db_index=True, max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
